name: Release tutorials (prod)

on:
  push:
    tags:
    - 'v*'

env:
  AWS_REGION: 'us-west-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@v1

    - name: Validate      
      run: |
        cd validation
        npm install
        node validate.js

    - name: S3 sync (misc files)
      run: |
        aws s3 sync \
          content/tutorials \
          s3://${{ secrets.S3_BUCKET_NAME_PROD }}/content/tutorials/ \
          --no-progress \
          --acl public-read \
          --follow-symlinks \
          --delete \
          --metadata-directive REPLACE \
          --exclude '*.md' \
          --cache-control max-age=0,no-cache,no-store,must-revalidate

    - name: S3 sync (Markdown files)
      run: |
        aws s3 sync \
          content/tutorials \
          s3://${{ secrets.S3_BUCKET_NAME_PROD }}/content/tutorials/ \
          --no-progress \
          --acl public-read \
          --follow-symlinks \
          --delete \
          --metadata-directive REPLACE \
          --exclude '*' \
          --include '*.md' \
          --content-type 'text/markdown' \
          --cache-control max-age=0,no-cache,no-store,must-revalidate

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation \
          --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}" \
          --paths '/content/tutorials/*'
